name: AWS CDK example workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  AWS_REGION: "us-east-2"
# permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  synth:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v2
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT | jq

      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Install Dependencies
        id: install
        run: bun install
      - name: Synthesize CloudFormation Template
        id: synth
        run: bun run build
