name: Deploy AWS CDK infrastructure
on:
  push:
    branches:
      - "env/**"
  workflow_dispatch:
# permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  synth:
    environment: development
    env:
      CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
      CDK_DEFAULT_REGION: ${{ secrets.CDK_DEFAULT_REGION }}
      AWS_REGION: ${{ secrets.CDK_DEFAULT_REGION }}
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT | jq
      - name: Clone repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: Install Dependencies
        id: install
        run: npm ci
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Synthesize CloudFormation Template
        id: synth
        run: echo "building..."
      - name: Validate CloudFormation Template
        id: validate
        run: echo "validated"
      # - name: Deploy CloudFormation Template
      #   id: deploy
      #   run: bun run deploy
